### PR TITLE
9.3

### PR DESCRIPTION
**Pull request by zaquestion**

### CODE REVIEW

**Comment by adamryman** [comment]
What happens when you pass the your method an array with duplicate integer values?

Say [6, 6, 6, 0, 6] or [6, 0, 6, 6, 6] while looking for the value of 0.

**Comment by zaquestion** [comment]
comment above is fixed

**Comment by zaquestion** [comment]
@adamryman this LGTM?

**Comment by adamryman** [comment]
LGTM

**Pull request merged**
